{
 "title": "Kafka",
 "description": "Metrics for the Kafka cluster",
 "tags": [ "kafka" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Under Replicated Partitions",
   "type": "gauge",
   "description": "Shows the number of under replicated partitions for each topic. If any are greater than 1, make sure your broker servers for the topic are healthy. ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (topic)(kafka_topic_partition_under_replicated_partition)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Consumer Group Members",
   "type": "graph",
   "description": "Number of consumer groups ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "kafka_consumergroup_members" }
   ]
  },
  {
   "title": "Zookeeper Status",
   "type": "natel-discrete-panel",
   "description": "Determines if zookeeper is running based on whether zookeeper is maintaining partition replicas. Ensure zookeeper is running. ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(kafka_topic_partition_replicas)",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Messages (by Topic)",
   "type": "stat",
   "description": "Displays the total messages split by topic. ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "kafka_consumergroup_current_offset_sum",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Memory Usage ",
   "type": "graph",
   "description": "This is the memory usage of the Prometheus program. If the system runs out of memory, Kafka will crash. ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes - node_memory_MemFree_bytes - node_memory_Buffers_bytes - node_memory_Cached_bytes)/node_memory_MemTotal_bytes",
     "legendFormat": "Prometheus"
    }
   ]
  },
  {
   "title": "Number of topic partition replicas",
   "type": "graph",
   "description": "This is the number of replicated partitions in different brokers. We want more than one replication for a more secure system. ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_topic_partition_replicas)"
    }
   ]
  },
  {
   "title": "Consumer Lag",
   "type": "graph",
   "description": "This is the total lag time for the consumers receiving messages in the kafka cluster. ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "-kafka_consumergroup_lag_sum" }
   ]
  },
  {
   "title": "Number of Brokers",
   "type": "stat",
   "description": "This is the number of brokers in the kafka cluster. ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "sum(kafka_brokers)" }
   ]
  },
  {
   "title": "CPU Usage Percentage",
   "type": "stat",
   "description": "This is the percent of CPU usage for your system. Keep it lower than 80% for a buffer. If this percentage hits 100%, kafka will have large performance issues. ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (instance,mode) (irate(node_cpu_seconds_total{mode='system'}[5m])) *500"
    }
   ]
  },
  {
   "title": "Amount of available space",
   "type": "stat",
   "description": "This shows the total space available on your computer. Make sure to have more than 100 GB to meet operational standards.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "Max(node_filesystem_avail_bytes)"
    }
   ]
  },
  {
   "title": "Total Messages",
   "type": "stat",
   "description": "Total messages received since cluster opened.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "Messages" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_current_offset_sum)"
    }
   ]
  }
 ]
}